var g_preload_img_arr = new Array( 
            "img/asta8.png", "img/asta7.png",
            "img/asta3.png", "img/asta4.png",
            "img/astapasso.png", "img/asta3_ro.png",
            "img/asta7_ro.png", "img/asta8_ro.png",
            "img/astapasso_ro.png", "img/asta5.png",
            "img/asta4_ro.png", "img/asta0.png",
            "img/asta9.png", "img/asta5_ro.png",
            "img/astalascio.png", "img/astapashalf.png",
            "img/asta0_ro.png", "img/asta9_ro.png",
            "img/asta6.png", "img/asta1.png",
            "img/astalascio_ro.png", "img/asta2.png",
            "img/astapashalf_ro.png", "img/asta6_ro.png",
            "img/asta1_ro.png", "img/astaptsub.png",
            "img/asta2_ro.png", "img/astaptsub_ro.png",
            "img/asta8.png", "img/asta7.png",
            "img/asta3.png", "img/asta4.png",
            "img/astapasso.png", "img/asta3_ro.png",
            "img/asta7_ro.png", "img/asta8_ro.png",
            "img/astapasso_ro.png", "img/asta5.png",
            "img/asta4_ro.png", "img/asta0.png",
            "img/asta9.png", "img/asta5_ro.png",
            "img/astalascio.png", "img/astapashalf.png",
            "img/asta0_ro.png", "img/asta9_ro.png",
            "img/asta6.png", "img/asta1.png",
            "img/astalascio_ro.png", "img/asta2.png",
            "img/astapashalf_ro.png", "img/asta6_ro.png",
            "img/asta1_ro.png", "img/astaptsub.png",
            "img/asta2_ro.png", "img/astaptsub_ro.png");
var g_preload_imgsz_arr = new Array( 
            "2.3", "4.7", "7.0", "9.2", "11.3", "13.4", "15.5", "17.6",
            "19.6", "21.6", "23.5", "25.3", "27.1", "28.8", "30.6", "32.2",
            "33.8", "35.4", "37.0", "38.5", "40.1", "41.7", "43.1", "44.6",
            "46.0", "47.4", "48.8", "50.0", "52.3", "54.7", "57.0", "59.2",
            "61.3", "63.4", "65.5", "67.6", "69.6", "71.6", "73.5", "75.3",
            "77.1", "78.8", "80.6", "82.2", "83.8", "85.4", "87.0", "88.5",
            "90.1", "91.7", "93.1", "94.6", "96.0", "97.4", "98.8", "100.0");
