var g_preload_img_arr = new Array( 
            "img/asta_en-en.png", "img/asta4-en.png",
            "img/asta5-en.png", "img/asta1-en.png",
            "img/asta3-en.png", "img/asta2-en.png",
            "img/astapasso-en.png", "img/astapasso_ro-en.png",
            "img/asta4_ro-en.png", "img/asta5_ro-en.png",
            "img/asta3_ro-en.png", "img/asta8-en.png",
            "img/asta7-en.png", "img/asta1_ro-en.png",
            "img/asta2_ro-en.png", "img/asta9-en.png",
            "img/asta0-en.png", "img/astalascio-en.png",
            "img/asta8_ro-en.png", "img/asta7_ro-en.png",
            "img/astaptsub-en.png", "img/asta6-en.png",
            "img/asta9_ro-en.png", "img/astalascio_ro-en.png",
            "img/asta0_ro-en.png", "img/astapashalf-en.png",
            "img/asta6_ro-en.png", "img/astaptsub_ro-en.png",
            "img/astapashalf_ro-en.png", "img/asta_en-en.png",
            "img/asta4-en.png", "img/asta5-en.png",
            "img/asta1-en.png", "img/asta3-en.png",
            "img/asta2-en.png", "img/astapasso-en.png",
            "img/astapasso_ro-en.png", "img/asta4_ro-en.png",
            "img/asta5_ro-en.png", "img/asta3_ro-en.png",
            "img/asta8-en.png", "img/asta7-en.png",
            "img/asta1_ro-en.png", "img/asta2_ro-en.png",
            "img/asta9-en.png", "img/asta0-en.png",
            "img/astalascio-en.png", "img/asta8_ro-en.png",
            "img/asta7_ro-en.png", "img/astaptsub-en.png",
            "img/asta6-en.png", "img/asta9_ro-en.png",
            "img/astalascio_ro-en.png", "img/asta0_ro-en.png",
            "img/astapashalf-en.png", "img/asta6_ro-en.png",
            "img/astaptsub_ro-en.png", "img/astapashalf_ro-en.png");
var g_preload_imgsz_arr = new Array( 
            "13.7", "15.3", "16.9", "18.4", "19.9", "21.4", "22.8", "24.2",
            "25.7", "27.0", "28.4", "29.8", "31.1", "32.4", "33.8", "35.0",
            "36.3", "37.6", "38.8", "40.0", "41.2", "42.4", "43.5", "44.7",
            "45.8", "46.9", "47.9", "49.0", "50.0", "63.7", "65.3", "66.9",
            "68.4", "69.9", "71.4", "72.8", "74.2", "75.7", "77.0", "78.4",
            "79.8", "81.1", "82.4", "83.8", "85.0", "86.3", "87.6", "88.8",
            "90.0", "91.2", "92.4", "93.5", "94.7", "95.8", "96.9", "97.9",
            "99.0", "100.0");
